llm:
  _target_: habitat_llm.llm.gemma_provider.GemmaProvider
  _partial_: True

generation_params:
  model: "llava-1.5"
  temperature: 0.2
  max_tokens: 128

system_message: 'You are an expert at task planning.'
system_tag: ""
user_tag: "USER:"
assistant_tag: "ASSISTANT:"
eot_tag: "\n"
keep_message_history: False
verbose: True
use_image_input: True
save_prompt_images: False
